# Generated by Django 5.0.7 on 2024-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('received_from', models.CharField(max_length=255)),
                ('sum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signature', models.CharField(max_length=255)),
                ('payment_details', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
